# deploy databases container with mariadb, mysql and postgres services with data persistence and setting user and password
version: '3'
name: Locations API
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dbadmin
      POSTGRES_DB: locations_api
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  locations_api:
    image: locations_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres     

volumes:
  postgres_data: {}
